// Auto-generated by the postman-to-k6 converter

import "./../libs/shim/core.js";
import "./../libs/shim/urijs.js";
import http from 'k6/http';
import { group } from "k6";
import {env} from "./env.js"

export let options = { maxRedirects: 4 };
const Request = Symbol.for("request");


export function setup() {



}

export default function() {

    let loginBody = {
       username: "user_test@gmail.com", password: "12345"

    }

    console.log("login body: ");
    console.log(loginBody);
    let res = http.post(env.baseUrl + "/user/login", JSON.stringify(loginBody), {
        headers: { 'Content-Type': 'application/json' },
     });

     console.log("login res: ");
     console.log(res.json());

}
