// Auto-generated by the postman-to-k6 converter

import "./../libs/shim/core.js";
import "./../libs/shim/urijs.js";
import http from 'k6/http';
import { group } from "k6";
import {env} from "./env.js"

export let options = { maxRedirects: 4 };
const Request = Symbol.for("request");
let username = "load_test@loadtest@tiggomark.com.br";
let password = "password"

export function setup() {

  let registerData = {username: env.defaultUsername, password: env.defaultPassword, email: env.defaultUsername };
  console.log("register default user...");
  let res = http.post(env.baseUrl+"/user/register", JSON.stringify(registerData), {
    headers: { 'Content-Type': 'application/json' },
  });
  console.log("login response: ");
  console.log(res.json());

}

export default function() {

    let loginBody = {
        username: env.defaultUsername,
        password: env.defaultPassword

    }

    console.log("login body: ");
    console.log(loginBody);
    let res = http.post(env.baseUrl + "/user/login", JSON.stringify(loginBody), {
        headers: { 'Content-Type': 'application/json' },
     });

     console.log("login res: ");
     console.log(res.json());

}
