// Auto-generated by the postman-to-k6 converter

import "./../libs/shim/core.js";
import "./../libs/shim/urijs.js";
import {env} from "./env.js"
import http from 'k6/http';
import { group } from "k6";

export let options = { maxRedirects: 4 };
const Request = Symbol.for("request");

export function setup() {

}

export default function() {

    let username =  "load_teste_" + new Date().getTime() + "@loadteste.tiggomark.com.br";
    let registerBody = {
        username: username,
        email: username,
        password: env.defaultPassword

    }
    let res = http.post(env.baseUrl + "/user/register", JSON.stringify(registerBody), {
        headers: { 'Content-Type': 'application/json' },
     });

     console.log("res register: ");
     console.log(res);

}
