// Auto-generated by the postman-to-k6 converter

import "./../libs/shim/core.js";
import "./../libs/shim/urijs.js";
import {env} from "./env.js"
import http from 'k6/http';
import { group } from "k6";
import loginTest from './login.js'
import registerTest from './register.js'

export let options = { maxRedirects: 4 };
const Request = Symbol.for("request");

export function setup() {

}

export default function() {

group("Login test", () => {
 loginTest();
 })

 group("Register test", () => {
  registerTest();
  })

}
